# 예제 3.01-05: 파이토치 텐서 기초

## 학습목표
1. **텐서(Tensor)의 개념** 이해하기 - 파이토치에서 데이터를 다루는 기본 단위
2. **다양한 텐서 생성 방법** 익히기 - `torch.tensor()`, `torch.Tensor()`, `torch.LongTensor()`, `torch.FloatTensor()`
3. **텐서의 주요 속성** 파악하기 - shape, dtype, device
4. **텐서의 차원 변환** 방법 학습하기 - `reshape()`
5. **GPU 가속 사용법** 이해하기 - CUDA(NVIDIA) 및 MPS(Apple Silicon)

---

#### 예제 3.01 텐서 생성

**텐서(Tensor)란?**
- 다차원 배열을 표현하는 파이토치의 핵심 자료구조
- NumPy의 ndarray와 유사하지만, GPU 연산을 지원
- 딥러닝에서 데이터, 가중치, 기울기 등을 저장하는 데 사용

In [1]:
import torch

# torch.tensor(): 파이썬 리스트로부터 텐서 생성 (자료형 자동 추론)
print(torch.tensor([1, 2, 3]))  # 1차원 텐서 (정수형)

# torch.Tensor(): 기본 FloatTensor 생성 (32비트 부동소수점)
print(torch.Tensor([[1, 2, 3], [4, 5, 6]]))  # 2차원 텐서 (2x3 행렬)

# torch.LongTensor(): 64비트 정수형 텐서 생성 (인덱스, 레이블에 주로 사용)
print(torch.LongTensor([1, 2, 3]))

# torch.FloatTensor(): 32비트 부동소수점 텐서 생성 (가장 일반적)
print(torch.FloatTensor([1, 2, 3]))

tensor([1, 2, 3])
tensor([[1., 2., 3.],
        [4., 5., 6.]])
tensor([1, 2, 3])
tensor([1., 2., 3.])


---

#### 예제 3.02 텐서 속성

**텐서의 주요 속성**
- `shape`: 텐서의 차원 크기 (예: (1, 2)는 1행 2열)
- `dtype`: 텐서의 데이터 타입 (예: torch.float32)
- `device`: 텐서가 저장된 장치 (cpu 또는 cuda)

In [5]:
import torch

# torch.rand(): 0~1 사이의 균일 분포에서 무작위 값으로 텐서 생성
tensor = torch.rand(1, 2)  # 1행 2열의 랜덤 텐서

print(tensor)         # 텐서 값 출력
print(tensor.shape)   # 텐서의 크기/형태: torch.Size([1, 2])
print(tensor.dtype)   # 데이터 타입: torch.float32 (기본값)
print(tensor.device)  # 저장 장치: cpu (기본값)

tensor([[0.1707, 0.1203]])
torch.Size([1, 2])
torch.float32
cpu


---

#### 예제 3.03 텐서 차원 변환

**reshape() 메서드**
- 텐서의 형태(차원)를 변경
- 전체 원소 개수는 동일해야 함 (예: 1x2 → 2x1)
- 신경망에서 입력 데이터의 형태를 맞출 때 자주 사용

In [6]:
import torch

# 1행 2열의 랜덤 텐서 생성
tensor = torch.rand(1, 2)
print(tensor)        # 텐서 값 출력
print(tensor.shape)  # 원래 형태: torch.Size([1, 2])

tensor([[0.6785, 0.6708]])
torch.Size([1, 2])


In [7]:
# reshape()으로 텐서 형태 변환: (1, 2) → (2, 1)
# 전체 원소 수 유지: 1*2 = 2*1 = 2
tensor = tensor.reshape(2, 1)
print(tensor)        # 변환된 텐서 값
print(tensor.shape)  # 새로운 형태: torch.Size([2, 1])

tensor([[0.6785],
        [0.6708]])
torch.Size([2, 1])


---

#### 예제 3.04 텐서 자료형 설정

**dtype 매개변수**
- 텐서 생성 시 데이터 타입을 명시적으로 지정
- 주요 자료형:
  - `torch.float` (= torch.float32): 기본 부동소수점
  - `torch.double` (= torch.float64): 높은 정밀도
  - `torch.long` (= torch.int64): 정수형 (인덱스용)
  - `torch.bool`: 불리언

In [8]:
import torch

# dtype 매개변수로 텐서의 자료형을 명시적으로 지정
# torch.float = torch.float32 (32비트 부동소수점)
tensor = torch.rand((3, 3), dtype=torch.float)
print(tensor)  # 3x3 float32 텐서

tensor([[0.8214, 0.5893, 0.0786],
        [0.9843, 0.3083, 0.1953],
        [0.4483, 0.3596, 0.0693]])


---

#### 예제 3.05 텐서 GPU 장치 설정 (CUDA)

**GPU 가속**
- 딥러닝 연산을 GPU에서 수행하면 CPU 대비 수십~수백 배 빠름
- **CUDA**: NVIDIA GPU를 위한 병렬 컴퓨팅 플랫폼
- `torch.cuda.is_available()`: CUDA 사용 가능 여부 확인
- `device` 매개변수로 텐서 저장 위치 지정

In [ ]:
import torch

# CUDA 사용 가능 여부에 따라 device 설정
# NVIDIA GPU가 있으면 "cuda", 없으면 "cpu"
device = "cuda" if torch.cuda.is_available() else "cpu"

# CPU에 저장되는 텐서 (기본값)
cpu = torch.FloatTensor([1, 2, 3])

# GPU(CUDA)에 직접 저장되는 텐서
# 주의: CUDA가 없으면 에러 발생
gpu = torch.cuda.FloatTensor([1, 2, 3])

# device 매개변수를 사용한 텐서 생성 (권장 방법)
# 자동으로 적절한 장치에 텐서 생성
tensor = torch.rand((1, 1), device=device)

print(device)  # 현재 사용 중인 장치
print(cpu)     # CPU 텐서
print(gpu)     # GPU 텐서
print(tensor)  # device에 따라 생성된 텐서

cpu
tensor([1., 2., 3.])
tensor([[0.4996]])


---

#### 예제 3.05 텐서 GPU 장치 설정 (Apple Silicon: MPS)

**MPS (Metal Performance Shaders)**
- Apple Silicon (M1, M2 등) Mac에서 GPU 가속 지원
- PyTorch 1.12부터 MPS 백엔드 지원
- `torch.backends.mps.is_available()`: MPS 사용 가능 여부 확인

In [ ]:
# 애플 실리콘이 탑재된 맥 사용자의 경우
import torch

# MPS 사용 가능 여부 확인
# is_available(): MPS 지원 여부, is_built(): PyTorch가 MPS로 빌드되었는지
device = "mps" if torch.backends.mps.is_available() and torch.backends.mps.is_built() else "cpu"

# CPU 텐서 생성
cpu = torch.FloatTensor([1, 2, 3])

# MPS 장치에 텐서 생성 (Apple GPU 가속)
mps = torch.rand((1, 1), device=device)

print(device)  # 사용 중인 장치: mps 또는 cpu
print(mps)     # MPS 또는 CPU에 저장된 텐서